# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 18:36
from __future__ import unicode_literals

import core.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', core.models.LowerCaseCharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.'), django.core.validators.RegexValidator(b'^(.){5,}$', b'A minimum of 5 characters are required.'), django.core.validators.RegexValidator(b'^[a-zA-Z]', b'Must start with a letter.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, default=b'', max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, default=b'', max_length=300, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
