# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160327_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
