# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:57
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160401_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=core.models.LowerCaseCharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.'), django.core.validators.RegexValidator(b'^(.){5,}$', b'A minimum of 5 characters are required.'), django.core.validators.RegexValidator(b'^[a-zA-Z]', b'Must start with a letter.')]),
        ),
    ]
