# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 10:24
from __future__ import unicode_literals

import core.fields
import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.models.LowerCaseCharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(b'^[a-z0-9+#-.]*$', b'Only a-z0-9+#-. characters are allowed.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_source', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, default=b'', max_length=10000)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('filename', core.fields.RestrictedVideoField(null=True, upload_to=b'videos/file/')),
                ('thumbnail', core.fields.RestrictedNonAnimatedImageField(blank=True, null=True, upload_to=b'uploads/videos/thumbnails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytic', serialize=False, to='videos.Video')),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='videos.Video')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('likes_register', models.ManyToManyField(related_name='video_likes', through='videos.Like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='videos.Tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Rating'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'rating')]),
        ),
    ]
