# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:47
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='videos.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=core.models.LowerCaseCharField(max_length=30, validators=[django.core.validators.RegexValidator(b'^[a-z0-9+#-.]*$', b'Only a-z0-9+#-. characters are allowed.')]),
        ),
    ]
