# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=b'uploads/videos/thumbnails'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
