# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 22:12
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160508_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=core.fields.RestrictedNonAnimatedImageField(blank=True, null=True, upload_to=b'uploads/videos/thumbnails'),
        ),
    ]
