# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:18
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160325_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('video', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videos.Video')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='analytic',
        ),
        migrations.DeleteModel(
            name='VideoAnalytic',
        ),
    ]
