# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 08:21
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20160508_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=core.fields.RestrictedVideoField(null=True, upload_to=b'videos/file/'),
        ),
    ]
