# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160326_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
