# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:18
from __future__ import unicode_literals

import annoying.fields
import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160403_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractRating',
            fields=[
                ('video', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='videos.Analytic')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractThumbnail',
            fields=[
                ('video', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thumbnail', serialize=False, to='videos.Video')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='analytic',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytic',
            name='unique_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='id_source',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(default='youtube', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=core.models.LowerCaseCharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(b'^[a-z0-9+#-.]*$', b'Only a-z0-9+#-. characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('abstractrating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.AbstractRating')),
            ],
            bases=('videos.abstractrating',),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('abstractthumbnail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videos.AbstractThumbnail')),
            ],
            bases=('videos.abstractthumbnail',),
        ),
    ]
