# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:06
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20160404_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractrating',
            name='video',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='videos.Video'),
        ),
    ]
