# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20160404_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id_source',
            field=models.CharField(max_length=100),
        ),
    ]
