# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20160501_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractrating',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='abstractthumbnail',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thumbnail', serialize=False, to='videos.Video'),
        ),
    ]
